/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/modules/contrib/addtoany/js/addtoany.js. */
(function(Drupal){'use strict';Drupal.behaviors.addToAny={attach:function(context,settings){if(context!==document&&window.a2a){a2a.init_all();}}};})(Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/modules/contrib/addtoany/js/addtoany.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/core/misc/jquery.once.bc.js. */
(function($,once){var deprecatedMessageSuffix="is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256";var originalJQOnce=$.fn.once;var originalJQRemoveOnce=$.fn.removeOnce;$.fn.once=function jQueryOnce(id){Drupal.deprecationError({message:"jQuery.once() ".concat(deprecatedMessageSuffix)});return originalJQOnce.apply(this,[id]);};$.fn.removeOnce=function jQueryRemoveOnce(id){Drupal.deprecationError({message:"jQuery.removeOnce() ".concat(deprecatedMessageSuffix)});return originalJQRemoveOnce.apply(this,[id]);};var drupalOnce=once;function augmentedOnce(id,selector,context){originalJQOnce.apply($(selector,context),[id]);return drupalOnce(id,selector,context);}
function remove(id,selector,context){originalJQRemoveOnce.apply($(selector,context),[id]);return drupalOnce.remove(id,selector,context);}
window.once=Object.assign(augmentedOnce,drupalOnce,{remove:remove});})(jQuery,once);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/core/misc/jquery.once.bc.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/modules/contrib/jquery_ui_effects/jquery.ui/ui/effects/effect-fade-min.js. */
!function(a){"function"==typeof define&&define.amd?define(["jquery","../version","../effect"],a):a(jQuery)}(function(a){return a.effects.define("fade","toggle",function(b,c){var d="show"===b.mode;a(this).css("opacity",d?0:1).animate({opacity:d?1:0},{queue:!1,duration:b.duration,easing:b.easing,complete:c})})});
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/modules/contrib/jquery_ui_effects/jquery.ui/ui/effects/effect-fade-min.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/modules/contrib/back_to_top/js/back_to_top.js. */
(function($){Drupal.behaviors.backtotop={attach:function(context,settings){var exist=$('#backtotop').length;if(exist==0){$("body",context).once('backtotop').each(function(){$('body').append("<button id='backtotop'>"+settings.back_to_top.back_to_top_button_text+"</button>");});}
backToTop();$(window).scroll(function(){backToTop();});$('#backtotop',context).once('backtotop').each(function(){$(this).click(function(){$("html, body").bind("scroll mousedown DOMMouseScroll mousewheel keyup",function(){$('html, body').stop();});$('html,body').animate({scrollTop:0},1200,'easeOutQuart',function(){$("html, body").unbind("scroll mousedown DOMMouseScroll mousewheel keyup");});return false;});});function backToTop(){if($(window).scrollTop()>settings.back_to_top.back_to_top_button_trigger){$('#backtotop').fadeIn();}else{$('#backtotop').fadeOut();}}}};})(jQuery);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/modules/contrib/back_to_top/js/back_to_top.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/modules/contrib/ckeditor_bootstrap_tabs/js/tabs.js. */
(function($,Drupal){"use strict";var initCKEditorTabs=function(){for(var i in CKEDITOR.instances){if(CKEDITOR.instances[i].document){var $tabComponents=$(CKEDITOR.instances[i].document.$.body).find('.bootstrap-tabs');tabsInit($tabComponents);}else{CKEDITOR.instances[i].on('instanceReady',function(instanceReadyEventObj){var editorInstanceData=CKEDITOR.instances[i].document.getBody();var $tabComponents=$(editorInstanceData.$).find('.bootstrap-tabs');tabsInit($tabComponents);});}}};Drupal.behaviors.ckeditorTabs={attach:function(context,settings){if(typeof CKEDITOR==='undefined'){var $viewTabs=$('.bootstrap-tabs',context);if($viewTabs.length>0){tabsInit($viewTabs);}
return;}
initCKEditorTabs();CKEDITOR.on("instanceReady",function(){initCKEditorTabs();});}};function tabsInit(elements){var $tabComponents=elements;if($tabComponents.length>0){$tabComponents.each(function(){var $tabs=$(this).find('.nav-tabs');$tabs.off('click','li > a').on('click','li > a',function(e){e.preventDefault();var link=$(this);link.parent().addClass('active').siblings().removeClass('active');link.parents('.bootstrap-tabs').find(link.attr('href')).addClass('active').siblings().removeClass('active');})});}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/modules/contrib/ckeditor_bootstrap_tabs/js/tabs.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/themes/contrib/bootstrap_barrio/js/barrio.js. */
(function($,Drupal){'use strict';Drupal.behaviors.bootstrap_barrio={attach:function(context,settings){var position=$(window).scrollTop();$(window).scroll(function(){if($(this).scrollTop()>50){$('body').addClass("scrolled");}
else{$('body').removeClass("scrolled");}
var scroll=$(window).scrollTop();if(scroll>position){$('body').addClass("scrolldown");$('body').removeClass("scrollup");}else{$('body').addClass("scrollup");$('body').removeClass("scrolldown");}
position=scroll;});$('.dropdown-item a.dropdown-toggle').on("click",function(e){$(this).next('ul').toggle();e.stopPropagation();e.preventDefault();});}};})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/themes/contrib/bootstrap_barrio/js/barrio.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.gs1.org/themes/contrib/bootstrap_barrio/js/affix.js. */
(function($,Drupal){'use strict';Drupal.behaviors.bootstrap_barrio_affix={attach:function(context,settings){var toggleAffix=function(affixElement,scrollElement,wrapper){var height=affixElement.outerHeight(),top=wrapper.offset().top;if(scrollElement.scrollTop()>=top){wrapper.height(height);affixElement.addClass("affix");}
else{affixElement.removeClass("affix");wrapper.height('auto');}};$('[data-toggle="affix"]').once().each(function(){var ele=$(this),wrapper=$('<div></div>');ele.before(wrapper);$(window).on('scroll resize',function(){toggleAffix(ele,$(this),wrapper);});toggleAffix(ele,$(window),wrapper);});}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.gs1.org/themes/contrib/bootstrap_barrio/js/affix.js. */;
